# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
##
## This file is a config file from which `ergogen` wil generate the PBCs, SVGs etc. I need those to build my keyboard.
##
X-common:
  keyboard.name: &X-Common-name "Snowflake: v1.0.1"

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Meta ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

meta:
  version: "v1.0.1"
  author: "\"Tygo van den Hurk\""

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Units ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: cx + 4
  py: cy + 4

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Points ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

points:
  rotate: 0
  zones:
    matrix:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        rotate: 5
        shift: [100, -100]
      columns:
        outer:
          rows.bottom.skip: true
          rows.top.skip: true
          key.col_net: P6
        pinky.key:
          col_net: P7
        ring.key:
          splay: -5
          origin: [-12, -19]
          stagger: 12
          col_net: P8
        middle.key:
          stagger: 5
          col_net: P9
        index.key:
          stagger: -6
          col_net: P21
        inner.key:
          stagger: -2
          col_net: P20
      rows:
        bottom:
          row_net: P4
        home:
          row_net: P0
        top:
          row_net: P1
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-22, -23]
      columns:
        near.key:
          col_net: P9
        home.key:
          col_net: P21
        far.key:
          col_net: P20
          width: 1.5kx
      rows:
        thumb:
          row_net: P5

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Outlines ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]

  keys:
    - what: rectangle
      fillet: 2
      where: true
      size: [1cx - 0.5, 1cy - 0.5]

  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_outer_home
          shift: [-0.5px, -0.5py]
        - ref: matrix_outer_home
          shift: [-0.5px, 0.5py]
        - ref: matrix_pinky_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_top
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_top
          shift: [1.5px, 0.5py]
        - ref: matrix_inner_top
          shift: [1.5px, -2.0py]
        - ref: thumbfan_far_thumb
          shift: [0.5px, 0.5py]
        - ref: thumbfan_far_thumb
          shift: [0.5px, -0.5py]
        - ref: thumbfan_far_thumb
          shift: [-0.5px, -0.5py]
        - ref: thumbfan_near_thumb
          shift: [0.5px, -0.5py]
        - ref: thumbfan_near_thumb
          shift: [-0.5px, -0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px, -0.5py]

  combo:
    - name: board
    - operation: subtract
      name: keys

  preview:
    - what: outline
      name: board
      operation: stack
    - what: outline
      name: keys
      operation: stack

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Cases ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

cases.production:
  - what: outline
    name: board
    extrude: 3
    operation: subtract
  - what: outline
    name: keys
    extrude: 6
    operation: add

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ PCBs ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

pcbs.production:

  outlines:
    main.outline: board
    keycaps:
      outline: keys
      layer: Eco1.User

  footprints:
    diode:
      what: sod-123w
      where: true
      params:
        from: "{{name}}"
        to: "{{row_net}}"
      adjust:
        shift: [-7.6, -1.6]
        rotate: 90
    choc:
      what: choc
      where: true
      params:
        keycaps: true
        hotswap: true
        reverse: true
        from: "{{col_net}}"
        to: "{{name}}"


    #` Micro controller

    promicro:
      what: promicro_pretty
      where:
        ref: matrix_inner_home
      adjust:
        shift: [22, 6.5]
        rotate: -90


    #` Reset switch

    wuerth-434121025816: 
      what: wuerth-434121025816
      where:
        ref: matrix_inner_home
        shift: [25, -21]
        rotate: 180
      params:
        r1: RST
        r2: GND


    #` Text

    front_text: &text
      what: text
      where: &textWhere
        ref: matrix_pinky_bottom
        shift: [15, -16]
        rotate: -19
      params: &textParams
        text: *X-Common-name
        justify: left
    back_text:
      <<: *text
      where:
        <<: *textWhere
        shift: [27.5, -20.5]
        rotate: -19
      params:
        <<: *textParams
        layer: B.SilkS
        justify: left mirror


    #` TRRS Connector

    connector: 
      what: trrs
      params:
        reverse: true
        symmetric: true
        A: VCC
        B: P2
        C: P3
        D: GND
      where:
        ref: matrix_inner_bottom
        shift: [30, 0]
        rotate: -90


    #` NixOS Logo
    # see: https://raw.githubusercontent.com/Tygo-van-den-Hurk/keyboard/refs/tags/v1.0.0/ergogen/images/nix.svg to 
    # know what color nix piece refers to what. 
    nix-piece-1: &icon #| Orange
      what: nix-piece
      params:
        scale: 0.03
      where:
        ref: matrix_inner_home
        shift: [-66.1, -41.83]
        rotate: -14.4
    nix-piece-2: #| Yellow
      <<: *icon
      where:
        ref: matrix_inner_home
        shift: [-49.16, -54.16]
        rotate: 45.6
    nix-piece-3: #| Green
      <<: *icon
      where:
        ref: matrix_inner_home
        shift: [-30, -45.65]
        rotate: 105.60
    nix-piece-4: #| Blue
      <<: *icon
      where:
        ref: matrix_inner_home
        shift: [-28, -25]
        rotate: 165.60
    nix-piece-5: #| Purple
      <<: *icon
      where:
        ref: matrix_inner_home
        shift: [-45, -12.6]
        rotate: 225.60
    nix-piece-6: #| Red
      <<: *icon
      where:
        ref: matrix_inner_home
        shift: [-64, -21.11]
        rotate: 285.60

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
