units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 4
  py: ky + 4

points:
  zones:
    matrix:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        rotate: 5
        shift: [100, -100]
      columns:
        outer:
          rows.bottom.skip: true
          rows.top.skip: true
        pinky:
        ring:
          key.splay: -5
          key.origin: [-12, -19]
          key.stagger: 12
        middle:
          key.stagger: 5
        index:
          key.stagger: -6
        inner:
          key.stagger: -2
      rows:
        bottom:
        home:
        top:
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-22, -23]
      columns:
        near:
        home:
        far:
          key:
            width: 1.5kx
      rows:
        thumb:
  rotate: -20

outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  
  keys:
    - what: rectangle
      where: true
      size: [kx - 0.5, ky - 0.5]

  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
      - ref: matrix_outer_home
        shift: [-0.5px, -0.5py]
      - ref: matrix_outer_home
        shift: [-0.5px, 0.5py]
      - ref: matrix_pinky_top
        shift: [-0.5px, 0.5py]
      - ref: matrix_ring_top
        shift: [-0.5px, 0.5py]
      - ref: matrix_middle_top
        shift: [-0.5px, 0.5py]
      - ref: matrix_middle_top
        shift: [0.5px, 0.5py]
      # - ref: matrix_index_top
      #   shift: [0.5px, 0.5py]
      - ref: matrix_inner_top
        shift: [0.5px, 0.5py]
      - ref: matrix_inner_top
        shift: [1.5px, 0.5py]
      - ref: matrix_inner_top
        shift: [1.5px, -2.0py]
      - ref: thumbfan_far_thumb
        shift: [0.5px, 0.5py]
      - ref: thumbfan_far_thumb
        shift: [0.5px, -0.5py]
      - ref: thumbfan_far_thumb
        shift: [-0.5px, -0.5py]
      - ref: thumbfan_near_thumb
        shift: [0.5px, -0.5py]
      - ref: thumbfan_near_thumb
        shift: [-0.5px, -0.5py]
      - ref: matrix_pinky_bottom
        shift: [-0.5px, -0.5py]

  combo:
    - name: board
    - operation: subtract
      name: keys

pcbs:
  production:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      promicro:
        what: promicro_pretty
        where:
          ref: matrix_inner_home
        adjust:
          shift: [22, 6.5]
          rotate: -90
