# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
##
## This file is a config file from which `ergogen` wil generate the PBCs, SVGs etc. I need those to build my keyboard.
##
X-common:
  keyboard.name: &X-Common-name "Version: v1.0.0"

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Meta ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

meta:
    version: "v1.0.0"
    author: "\"Tygo van den Hurk\""

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Units ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 4
  py: ky + 4

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Points ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

points:
  zones:
    matrix:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        rotate: 5
        shift: [100, -100]
      columns:
        outer:
          rows.bottom.skip: true
          rows.top.skip: true
          key.col_net: P6
        pinky.key:
          col_net: P7
        ring.key:
          splay: -5
          origin: [-12, -19]
          stagger: 12
          col_net: P8
        middle.key:
          stagger: 5
          col_net: P9
        index.key:
          stagger: -6
          col_net: P21
        inner.key:
          stagger: -2
          col_net: P20
      rows:
        bottom:
          row_net: P4
        home:
          row_net: P0
        top:
          row_net: P1
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-22, -23]
      columns:
        near.key:
          col_net: P21
        home.key:
          col_net: P20
        far.key:
          col_net: P19
          width: 1.5kx
      rows:
        thumb:
          row_net: P5
  rotate: -20

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Outlines ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]

  keys:
    - what: rectangle
      fillet: 2
      where: true
      size: [1cx - 0.5, 1cy - 0.5]

  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_outer_home
          shift: [-0.5px, -0.5py]
        - ref: matrix_outer_home
          shift: [-0.5px, 0.5py]
        - ref: matrix_pinky_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_top
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_top
          shift: [1.5px, 0.5py]
        - ref: matrix_inner_top
          shift: [1.5px, -2.0py]
        - ref: thumbfan_far_thumb
          shift: [0.5px, 0.5py]
        - ref: thumbfan_far_thumb
          shift: [0.5px, -0.5py]
        - ref: thumbfan_far_thumb
          shift: [-0.5px, -0.5py]
        - ref: thumbfan_near_thumb
          shift: [0.5px, -0.5py]
        - ref: thumbfan_near_thumb
          shift: [-0.5px, -0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px, -0.5py]

  combo:
    - name: board
    - operation: subtract
      name: keys

  preview:
    - what: outline
      name: board
      operation: stack
    - what: outline
      name: keys
      operation: stack

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Cases ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

cases.production:
  - what: outline
    name: board
    extrude: 3
    operation: subtract
  - what: outline
    name: keys
    extrude: 6
    operation: add

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ PCBs ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

pcbs.production:

  outlines:
    main.outline: board
    keycaps:
      outline: keys
      layer: Eco1.User

  footprints:
    diode:
      what: sod-123w
      where: true
      params:
        from: "{{name}}"
        to: "{{row_net}}"
      adjust:
        shift: [-7.6, -1.6]
        rotate: 90
    choc:
      what: choc
      where: true
      params:
        keycaps: true
        hotswap: true
        from: "{{col_net}}"
        to: "{{name}}"

    promicro:
      what: promicro_pretty
      where:
        ref: matrix_inner_home
      adjust:
        shift: [22, 6.5]
        rotate: -90

    wuerth-434121025816: # Reset switch
      what: wuerth-434121025816
      where:
        ref: matrix_inner_home
        shift: [25, -21]
        rotate: 0
      params:
        r1: RST
        r2: GND

    front_text: &text
      what: text
      where: &textWhere
        ref: matrix_pinky_bottom
        shift: [12, -15]
        rotate: -19
      params: &textParams
        text: *X-Common-name
        justify: left
    back_text:
      <<: *text
      where:
        <<: *textWhere
        shift: [27, -20]
        rotate: -19
      params:
        <<: *textParams
        layer: B.SilkS
        justify: left mirror
    safeText:
      <<: *text
      what: keepout
      params:
        points:
          - x: -0.5
            y: -2
          - x: 15.5
            y: -2
          - x: 15.5
            y: 2
          - x: -0.5
            y: 2

    connector: # TRRS Connector
      what: trrs
      params:
        reverse: true
        symmetric: true
        A: VCC
        B: P2
        C: P3
        D: GND
      where:
        ref: matrix_inner_bottom
        shift: [30, 0]
        rotate: -90

    nix-piece-1: &icon # orange
      what: nix-piece
      where:
        shift: [80, -151]
        rotate: -34
      params:
        scale: 0.03
    nix-piece-2: # yellow
      <<: *icon
      where:
        shift: [92.5, -168.2]
        rotate: 26
    nix-piece-3: # green
      <<: *icon
      where:
        shift: [113.95, -166.09]
        rotate: 86
    nix-piece-4: # blue
      <<: *icon
      where:
        shift: [123, -146.5]
        rotate: 146
    nix-piece-5: # purple
      <<: *icon
      where:
        shift: [110.5, -129.48]
        rotate: 206
    nix-piece-6: # red
      <<: *icon
      where:
        shift: [89, -131.5]
        rotate: 266


    # rust:
    #   <<: *icon
    #   what: rust

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
